### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'items' Windows incompatbility

### ISSUE THREAD

**Issue by hancockks** [bulkan/robotframework-requests#150]
There seems to be an incompatibility between the Create Session keyword and later being used by the Get Request keyword when run on a windows environment.  Below is the test case:

Setup Suite
    Create Session    mysession   ${BASE_URL}

Test Member Endpoint Default Functionality
    [Documentation]    Tests the /api/member servlet to check service status    
    Verify MSV Inserter Member Servlet In Normal Mode

Verify Member Servlet in Normal Mode
    [Documentation]    Calls the /api/member servlet to check for a 200 status and status:up
    [Arguments]    ${alias}
    ${resp}=    Get Request    ${alias}    ${MEMBER_PATH}    timeout=5
    Should be Equal As Numbers    ${resp.status_code}    200
    [return]    ${resp}

Linux results:
```20170303 09:40:10.731 - INFO - +-- START SUITE: Member-Servlet [ ]
==============================================================================
20170303 09:40:10.733 - INFO - +--- START SETUP: BuiltIn.Run Keywords [ Setup Suite ]
20170303 09:40:10.733 - INFO - +---- START KW: Setup Suite [ ]
20170303 09:40:10.734 - INFO - +----- START KW: RequestsLibrary.Create Session [ mysession | ${BASE_URL} ]
20170303 09:40:10.734 - INFO - Creating Session using : alias=mysession, url=http://192.168.215.148:8180/, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0
20170303 09:40:10.735 - DEBUG - Creating session: mysession
20170303 09:40:10.735 - DEBUG - Argument types are:
<type 'bool'>
20170303 09:40:10.735 - INFO - +----- END KW: RequestsLibrary.Create Session (1)
20170303 09:40:10.736 - INFO - +----- START KW: BuiltIn.Log [ Setup Suite | DEBUG ]
20170303 09:40:10.736 - DEBUG - Setup Suite
20170303 09:40:10.736 - INFO - +----- END KW: BuiltIn.Log (0)
20170303 09:40:10.736 - INFO - +---- END KW: Setup Suite (3)
20170303 09:40:10.737 - INFO - +--- END SETUP: BuiltIn.Run Keywords (4)
------------------------------------------------------------------------------
20170303 09:40:10.737 - INFO - +--- START TEST: Test Member Endpoint Default Functionality [ ]
------------------------------------------------------------------------------
20170303 09:40:10.738 - INFO - +---- START KW: Verify Member Servlet In Normal Mode [ ]
20170303 09:40:10.739 - INFO - +----- START KW: resource_member_servlet.Verify Member Servlet in Normal Mode [ mysession ]
20170303 09:40:10.740 - INFO - +------ START KW: RequestsLibrary.Get Request [ ${alias} | ${MEMBER_PATH} | timeout=5 ]
20170303 09:40:10.764 - INFO - Get Request using : alias=mysession, uri=/api/member, headers=None
20170303 09:40:10.767 - INFO - ${resp} = <Response [200]>
20170303 09:40:10.767 - INFO - +------ END KW: RequestsLibrary.Get Request (27)
20170303 09:40:10.767 - INFO - +------ START KW: BuiltIn.Should Be Equal As Numbers [ ${resp.status_code} | 200 ]
20170303 09:40:10.768 - INFO - Argument types are:
<type 'int'>
<type 'unicode'>
20170303 09:40:10.768 - INFO - +------ END KW: BuiltIn.Should Be Equal As Numbers (1)
```

Windows Result
```20170303 09:39:54.241 - INFO - +-- START SUITE: Member-Servlet [ ]
==============================================================================
20170303 09:39:54.244 - INFO - +--- START SETUP: BuiltIn.Run Keywords [ Setup Suite ]
20170303 09:39:54.245 - INFO - +---- START KW: Setup Suite [ ]
20170303 09:39:54.246 - INFO - +----- START KW: RequestsLibrary.Create Session [ mysession | ${BASE_URL} ]
20170303 09:39:54.246 - INFO - Creating Session using : alias=mysession, url=http://192.168.215.148:8180/, headers={}, cookies=None, auth=None, timeout=None, proxies=None, verify=False
20170303 09:39:54.246 - DEBUG - Creating session: mysession
20170303 09:39:54.247 - DEBUG - Argument types are:
<type 'bool'>
20170303 09:39:54.247 - INFO - +----- END KW: RequestsLibrary.Create Session (1)
20170303 09:39:54.247 - INFO - +----- START KW: BuiltIn.Log [ Setup Suite | DEBUG ]
20170303 09:39:54.248 - DEBUG - Setup Suite
20170303 09:39:54.248 - INFO - +----- END KW: BuiltIn.Log (1)
20170303 09:39:54.248 - INFO - +---- END KW: Setup Suite (3)
20170303 09:39:54.248 - INFO - +--- END SETUP: BuiltIn.Run Keywords (4)
------------------------------------------------------------------------------
20170303 09:39:54.249 - INFO - +--- START TEST: Test Member Endpoint Default Functionality [ ]
------------------------------------------------------------------------------
20170303 09:39:54.251 - INFO - +---- START KW: Verify Member Servlet In Normal Mode [ ]
20170303 09:39:54.252 - INFO - +----- START KW: resource_member_servlet.Verify Member Servlet in Normal Mode [ mysession ]
20170303 09:39:54.253 - INFO - +------ START KW: RequestsLibrary.Get Request [ ${alias} | ${MEMBER_PATH} | timeout=5 ]
20170303 09:39:54.258 - FAIL - AttributeError: 'unicode' object has no attribute 'items'
20170303 09:39:54.258 - DEBUG - Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 172, in get_request
    response = self._get_request(session, uri, headers, params, redir)
  File "C:\Python27\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 473, in _get_request
    allow_redirects=allow_redirects)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\Lib\site-packages\requests\models.py", line 296, in prepare
    self.prepare_headers(headers)
  File "C:\Python27\Lib\site-packages\requests\models.py", line 407, in prepare_headers
    self.headers = CaseInsensitiveDict((to_native_string(name), value) for name, value in headers.items())
20170303 09:39:54.258 - INFO - +------ END KW: RequestsLibrary.Get Request (5)
20170303 09:39:54.258 - INFO - +----- END KW: resource_member_servlet.Verify Member Servlet in Normal Mode (6)
```

**Comment by hancockks** [comment]
As a followup, perhaps the above is a red herring.

I noticed in the unit tests that there are no tests for the timeout parameter.  Removing the timeout parameter and it now passes on windows:

```
20170303 11:45:38.345 - INFO - +--- START TEST: Test Member Endpoint Default Functionality [ ]
------------------------------------------------------------------------------
20170303 11:45:38.362 - INFO - +---- START KW: Verify Member Servlet In Normal Mode [ ]
20170303 11:45:38.369 - INFO - +----- START KW: resource_member_servlet.Verify Member Servlet in Normal Mode [ msvinserter ]
20170303 11:45:38.388 - INFO - +------ START KW: RequestsLibrary.Get Request [ ${alias} | ${MEMBER_PATH} ]
20170303 11:45:38.394 - INFO - Starting new HTTP connection (1): 192.168.215.148
20170303 11:45:38.402 - INFO - Get Request using : alias=mysession, uri=/api/member, headers=None
20170303 11:45:38.402 - INFO - ${resp} = <Response [200]>
20170303 11:45:38.402 - INFO - +------ END KW: RequestsLibrary.Get Request (14)
20170303 11:45:38.403 - INFO - +------ START KW: BuiltIn.Should Be Equal As Numbers [ ${resp.status_code} | 200 ]
20170303 11:45:38.404 - INFO - Argument types are:
<type 'int'>
<type 'unicode'>
20170303 11:45:38.404 - INFO - +------ END KW: BuiltIn.Should Be Equal As Numbers (1)
20170303 11:45:38.405 - INFO - +------ START KW: BuiltIn.Should Contain [ ${resp.text} | status:up ]
```

**Comment by hancockks** [comment]
Moving timeout=5 to the Create Session keyword causes a similar error. 
```
20170303 11:52:59.374 - INFO - +--- START SETUP: BuiltIn.Run Keywords [ Setup Suite ]
20170303 11:52:59.381 - INFO - +---- START KW: Setup Suite [ ]
20170303 11:52:59.389 - INFO - +----- START KW: resource_member_servlet.Get Headers [ ]
20170303 11:52:59.440 - INFO - +------ START KW: BuiltIn.Create Dictionary [ Accept=*/* ]
20170303 11:52:59.443 - INFO - &{headers} = { Accept=*/* }
20170303 11:52:59.443 - INFO - +------ END KW: BuiltIn.Create Dictionary (3)
20170303 11:52:59.444 - INFO - &{headers} = { Accept=*/* }
20170303 11:52:59.444 - INFO - +----- END KW: resource_member_servlet.Get Headers (56)
20170303 11:52:59.444 - INFO - +----- START KW: RequestsLibrary.Create Session [ mysession | ${BASE_URL} | timeout=5 ]
20170303 11:52:59.445 - INFO - Creating Session using : alias=mysession, url=http://192.168.215.148:8180/, headers={}, cookies=None, auth=None, timeout=5, proxies=None, verify=False
20170303 11:52:59.445 - DEBUG - Creating session: mysession
20170303 11:52:59.446 - DEBUG - Argument types are:
<type 'bool'>
20170303 11:52:59.446 - INFO - +----- END KW: RequestsLibrary.Create Session (2)
20170303 11:52:59.446 - INFO - +----- START KW: BuiltIn.Log [ Setup Suite | DEBUG ]
20170303 11:52:59.447 - DEBUG - Setup Suite
20170303 11:52:59.447 - INFO - +----- END KW: BuiltIn.Log (1)
20170303 11:52:59.447 - INFO - +---- END KW: Setup Suite (67)
20170303 11:52:59.447 - INFO - +--- END SETUP: BuiltIn.Run Keywords (74)
------------------------------------------------------------------------------
20170303 11:52:59.447 - INFO - +--- START TEST: Test Member Endpoint Default Functionality [ ]
------------------------------------------------------------------------------
20170303 11:52:59.448 - INFO - +---- START KW: Verify Member Servlet In Normal Mode [ ]
20170303 11:52:59.448 - INFO - +----- START KW: resource_member_servlet.Verify Member Servlet in Normal Mode [ mysession ]
20170303 11:52:59.451 - INFO - +------ START KW: RequestsLibrary.Get Request [ ${alias} | ${MEMBER_PATH} ]
20170303 11:52:59.628 - INFO - Starting new HTTP connection (1): 192.168.215.148
20170303 11:53:00.004 - FAIL - TypeError: a float is required
20170303 11:53:00.004 - DEBUG - Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 172, in get_request
    response = self._get_request(session, uri, headers, params, redir)
  File "C:\Python27\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 473, in _get_request
    allow_redirects=allow_redirects)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\Lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\Lib\site-packages\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Python27\Lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "C:\Python27\Lib\site-packages\requests\packages\urllib3\connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Python27\Lib\site-packages\requests\packages\urllib3\connection.py", line 167, in connect
    conn = self._new_conn()
  File "C:\Python27\Lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python27\Lib\site-packages\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.settimeout(timeout)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
20170303 11:53:00.004 - INFO - +------ END KW: RequestsLibrary.Get Request (553)
20170303 11:53:00.004 - INFO - +----- END KW: resource_member_servlet.Verify Member Servlet in Normal Mode (556)
20170303 11:53:00.004 - INFO - +---- END KW: Verify Member Servlet In Normal Mode (556)
```

**Comment by vkosuri** [comment]
@hancockks did you find any solution for this?

**Comment by hancockks** [comment]
My only solution was to remove the timeout named parameter.

**Comment by bulkan** [comment]
This is the line where timeout is converted to float;

https://github.com/bulkan/robotframework-requests/blob/master/src/RequestsLibrary/RequestsKeywords.py#L135

**Comment by vkosuri** [comment]
@hancockks can you tried setting timeout to float member for example

``` Robotframework
Verify Member Servlet in Normal Mode
[Documentation] Calls the /api/member servlet to check for a 200 status and status:up
[Arguments] ${alias}
${resp}= Get Request ${alias} ${MEMBER_PATH} timeout=5.0
Should be Equal As Numbers ${resp.status_code} 200
[return] ${resp}
```

**Comment by vkosuri** [comment]
@hancockks I am closing this issue, if you need any further help please feel free to reopen this issue.

**Comment by hancockks** [comment]
I don't see how you're closing the issue.  There's clearly a problem when run on the windows platform.

I did try adding a timeout=5.0 to the Get Request and it still fails as above:

```KEYWORD ${resp} = RequestsLibrary . Get Request ${alias}, ${MEMBER_PATH}, timeout=5.0
Documentation:	
Send a GET request on the session object found using the
Start / End / Elapsed:	20170310 16:10:17.989 / 20170310 16:10:17.996 / 00:00:00.007
16:10:17.995	FAIL	AttributeError: 'unicode' object has no attribute 'items'```

**Comment by vkosuri** [comment]
@hancockks i have retried your problem on my windows machine. It is working fine as expected. could you try below example let me know.

```Robotframework
*** Settings ***
Library  Collections
Library  String
Library  RequestsLibrary
Library  OperatingSystem

*** Test Cases ***
Get Requests
    [Tags]  get
    Create Session  google  http://www.google.com
    Create Session  github  https://api.github.com
    ${resp}=  Get Request  google  /    timeout=5
    Should Be Equal As Strings  ${resp.status_code}  200
    ${resp}=  Get Request  github  /users/bulkan    timeout=5
    Should Be Equal As Strings  ${resp.status_code}  200
    Dictionary Should Contain Value  ${resp.json()}  Bulkan Evcimen
```

```html
KEYWORD ${resp} = RequestsLibrary . Get Request google, /, timeout=5
Documentation: 	

Send a GET request on the session object found using the
Start / End / Elapsed: 	20170311 05:32:17.522 / 20170311 05:32:18.684 / 00:00:01.162
05:32:17.522 	TRACE 	Arguments: [ 'google' | '/' | timeout='5' ] 	
05:32:17.529 	INFO 	Starting new HTTP connection (1): www.google.com 	
05:32:18.111 	DEBUG 	"GET / HTTP/1.1" 302 261 	
05:32:18.118 	INFO 	Starting new HTTP connection (1): www.google.co.in 	
05:32:18.675 	DEBUG 	"GET /?gfe_rd=cr&ei=iT7DWLepOOzT8gew3oHABg HTTP/1.1" 200 4899 	
05:32:18.682 	INFO 	Get Request using : alias=google, uri=/, headers=None 	
05:32:18.683 	TRACE 	Return: <Response [200]> 	
05:32:18.683 	INFO 	${resp} = <Response [200]>
```

**Comment by hancockks** [comment]
vkosuir, thanks for trying on Windows.  Seeing the same problem, Windows 7.

```
C:\Users\khancock\Dev\InternalTools\Automation>python.exe -m robot.run --debugfile debug.txt test.robot
==============================================================================
Test
==============================================================================
Get Requests                                                          | FAIL |
AttributeError: 'unicode' object has no attribute 'items'
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Debug:   C:\Users\khancock\Dev\InternalTools\Automation\debug.txt
Output:  C:\Users\khancock\Dev\InternalTools\Automation\output.xml
Log:     C:\Users\khancock\Dev\InternalTools\Automation\log.html
Report:  C:\Users\khancock\Dev\InternalTools\Automation\report.html
```

I added a Get Requests without the timeout prior to your line just to double-check...here's the debug.txt log

```
20170313 09:48:19.730 - INFO - +-- START KW: RequestsLibrary.Get Request [ google | / ]
20170313 09:48:19.878 - INFO - Get Request using : alias=google, uri=/, headers=None
20170313 09:48:19.878 - INFO - ${resp} = <Response [200]>
20170313 09:48:19.879 - INFO - +-- END KW: RequestsLibrary.Get Request (148)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20170313 09:48:19.879 - INFO - +-- START KW: RequestsLibrary.Get Request [ google | / | timeout=5 ]
20170313 09:48:19.881 - FAIL - AttributeError: 'unicode' object has no attribute 'items'
20170313 09:48:19.881 - DEBUG - Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 172, in get_request
    response = self._get_request(session, uri, headers, params, redir)
  File "C:\Python27\lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 473, in _get_request
    allow_redirects=allow_redirects)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\site-packages\requests\models.py", line 303, in prepare
    self.prepare_headers(headers)
  File "C:\Python27\lib\site-packages\requests\models.py", line 441, in prepare_headers
    for header in headers.items():
20170313 09:48:19.882 - INFO - +-- END KW: RequestsLibrary.Get Request (2)
------------------------------------------------------------------------------
20170313 09:48:19.884 - INFO - +- END TEST: Get Requests (155)
------------------------------------------------------------------------------
20170313 09:48:19.887 - INFO - + END SUITE: Test (294)
```

Here's the output of pip freeze from Python 2.7.13
```
apipkg==1.4
Appium-Python-Client==0.24
beautifulsoup4==4.5.3
boto==2.46.1
cassandra-driver==3.8.0
cffi==1.9.1
cluster==1.3.3
colorama==0.3.7
coverage==4.3.4
cryptography==1.7.2
decorator==4.0.11
docutils==0.13.1
enum34==1.1.6
execnet==1.4.1
funcsigs==1.0.2
futures==3.0.5
idna==2.4
ipaddress==1.0.18
jsonpatch==1.15
jsonpointer==1.10
lxml==3.4.4
mock==2.0.0
MySQL-python==1.2.5
paramiko==2.1.2
pbr==2.0.0
psycopg2==2.7
py==1.4.32
pyasn1==0.2.3
pycassa==1.11.2
pycparser==2.17
pyjolokia==0.3.1
PyMySQL==0.7.10
pytest==3.0.6
pytest-cov==2.4.0
pytest-pythonpath==0.7.1
pytest-xdist==1.15.0
requests==2.13.0
robotframework==3.0.2
robotframework-appiumlibrary==1.4.3
robotframework-archivelibrary==0.3.2
robotframework-databaselibrary==0.8.1
robotframework-ftplibrary==1.3
robotframework-httplibrary==0.4.2
robotframework-jmeterlibrary==1.1
robotframework-requests==0.3.9
robotframework-scplibrary==1.1.1
robotframework-selenium2library==1.8.0
robotframework-sshlibrary==2.1.3
robotframework-xvfb==1.2.2
sauceclient==0.2.1
scp==0.10.2
selenium==3.0.2
six==1.10.0
TestLink-API-Python-client==0.6.3
thrift==0.9.3
waitress==1.0.2
WebOb==1.7.1
WebTest==2.0.25
xvfbwrapper==0.2.9
```

**Comment by vkosuri** [comment]
ha i see you are running robot.run, instead could try like this?

```
pybot --loglevel TRACE --debugfile debug.txt test.robot
```

**Comment by hancockks** [comment]
Damn...you had me excited for a sec.

```
C:\Users\xxx\Automation>pybot --loglevel TRACE --debugfile debug.txt test.robot
==============================================================================
Test
==============================================================================
Get Requests                                                          | FAIL |
AttributeError: 'unicode' object has no attribute 'items'
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Debug:   C:\Users\xxx\Automation\debug.txt
Output:  C:\Users\xxx\Automation\output.xml
Log:     C:\Users\xxx\Automation\log.html
Report:  C:\Users\xxx\Automation\report.html
```

**Comment by vkosuri** [comment]
can you share ``test.robot`` file?

**Comment by hancockks** [comment]
Same one you asked me to try above.  The only difference is I duplicated line first Get Request line to remove the timeout to show it worked without the timeout but failed when the timeout was specified.
```
*** Settings ***
Library  Collections
Library  String
Library  RequestsLibrary
Library  OperatingSystem

*** Test Cases ***
Get Requests
    [Tags]  get
    Create Session  google  http://www.google.com
    Create Session  github  https://api.github.com
    ${resp}=  Get Request  google  /
    ${resp}=  Get Request  google  /    timeout=5
    Should Be Equal As Strings  ${resp.status_code}  200
    ${resp}=  Get Request  github  /users/bulkan    timeout=5
    Should Be Equal As Strings  ${resp.status_code}  200
    Dictionary Should Contain Value  ${resp.json()}  Bulkan Evcimen
```

**Comment by vkosuri** [comment]
hmm, I upgraded all the packages still my testcases are green

my packages are and also i see you are using ``robotframework-requests==0.3.5`` could you try to upgrade

`` pip install --upgrade robotframework-requests``

I having fallowing packages, the above test is working fine.
```
requests==2.13.0
requests-oauthlib==0.7.0
rest-commands==1.0.0
robotframework==3.0.2
robotframework-ncclient==0.1.0
robotframework-pabot==0.31
robotframework-requests==0.4.5
robotframework-ride==1.5.2.1
robotremoteserver==1.0.1
```

**Comment by hancockks** [comment]
Passes with robotframework-requests 0.4.6.  Apologies...must have a hard-coded version someplace.
